version: "3.8"

services:
  postgres:
    image: postgres
    container_name: restaurant-db
    environment:
      POSTGRES_DB: canva
      POSTGRES_USER: canva
      POSTGRES_PASSWORD: canva
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    container_name: restaurant-cache
    command: redis-server --requirepass canva --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
